version: '3'

services:

  db:
    image: postgres
    volumes:
      - ./local_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  back:
    build:
      context: ./back/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/src
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - '8000:8000'
    depends_on:
      - db

  front:
    image: node
    user: 'node'
    working_dir: /home/node/
    environment:
      - NODE_ENV=development
    volumes:
      - ./front:/home/node/
    ports:
      - '8080:8080'
    command: 'npm run serve'
